---
title: "Creating meta4"
output: creating_meta4
---

#Load library
```{r}

library(tidyverse)

```

#Data from study: Bryant (4)
Loading file report tsv file
```{r}
file_report_4 <- read_delim("./4_bryant_filereport_station_read_run_PRJNA318384_tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(file_report_4)
```

Select only necessary columns from file report
```{r}
file_report_4_select <- select(file_report_4, run_accession, scientific_name, Station)
file_report_4_select
```

Loading table from article tsv file
```{r}
article_table_4 <- read_delim("./4_bryant_excel.tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

```
Select only necessary columns from article file
```{r}
article_table_4_select <- select(article_table_4, -(Longitude: Latitude))
article_table_4_select
```





```{r}
meta4 <- left_join(file_report_4_select, article_table_4_select, by = "Station",
copy=FALSE, suffix=c("file_report_4","article_table_4"))
glimpse(meta4)
```

Change header name from run_accession to sample_id
```{r}
colnames(meta4)[2] <- "environment"
colnames(meta4)[1] <- "sample_id"
colnames(meta4)[3] <- "sample_alias"
glimpse(meta4)
```
Select columns for "global study" [READY TO MERGE]
```{r}
meta4_selected <- select(meta4, "sample_id", "environment", "sample_alias")
glimpse(meta4_selected)
```
Adding name of study as extra column [READY TO MERGE]
```{r}
meta4_2 <- add_column(meta4_selected, "study" = "J.A. Bryant et al. (2016)", .after = "sample_alias")
```


















