#!/usr/bin/env bash
#quality filter with fastp
for file in /cephyr/NOBACKUP/groups/snic2020-8-84/fastqfiles/*.fastq;
do
  file_name=$(echo $file | cut -d'/' -f 7)
  file_ID=$(echo $file_name | cut -d'_' -f 1)
  echo $file_ID

  sbatch /cephyr/NOBACKUP/groups/snic2020-8-84/scripts/fastp_filter.sh $file_ID
done
wait

declare -a already_exist=()

#for file in /Users/leti/Desktop/iGEM/modelling/metagenomics/test/*.gz;
#merging files/concatinate [temporary]
for file in /cephyr/NOBACKUP/groups/snic2020-8-84/temp_filteredfastq/*.gz;
do
  file_name=$(echo $file | xargs -n 1 basename)
  file_ID=$(echo $file_name | cut -d'_' -f 1)
  if [[ ! " ${already_exist[@]} " =~ " ${file_ID} " ]];
  then
    already_exist+=("$file_ID")
    cat "/cephyr/NOBACKUP/groups/snic2020-8-84/temp_filteredfastq/${file_ID}_filtered_1.fastq.gz" "/cephyr/NOBACKUP/groups/snic2020-8-84/temp_filteredfastq/${file_ID}_filtered_2.fastq.gz" >> /cephyr/NOBACKUP/groups/snic2020-8-84/temp_merged_filteredfastq/temp_merged_$file_ID.fastq.gz
  fi
done

#running humann2
for file in /cephyr/NOBACKUP/groups/snic2020-8-84/merged_filteredfastq/*.gz;
do
  file_name=$(echo $file | xargs -n 1 basename)
  file_ID=$(echo $file_name | cut -d'_' -f 1)
  echo $file_ID

 sbatch humann.sh $file_name $file_ID
done
wait
declare -a already_exist=()

sleep 60
