---
title: "R Notebook"
output: html_notebook
---

Load libraries
```{r}
library("tidyverse")
dummy <- data.frame(X = c("BphA1","BphB", "BphC", "BphD", "Puea"), Z =c(log10(0.018),log10(0.0031),log10(0.001),log10(0.0046),log10(10)))

dummy2 <- data.frame(X = c("BphA1","BphB", "BphC", "BphD", "Puea"), Z =c(log10(1.1),log10(0.38),log10(100),log10(100),log10(10)))


dummy = 
  dummy %>% 
  rename(enzyme = X)

head(dummy)

dummy2 =
  dummy2 %>%
  rename(enzyme = X)

head(dummy2)

```

```{r}
df_sens <- read_delim("C:/Users/Niklas/OneDrive/Dokument/iGEM/Modelling/R/sens_analysis_log.csv",
    ";", escape_double = FALSE, trim_ws = TRUE)



head(df_sens)
```

```{r}
df_sens = df_sens  %>% 
  pivot_longer(cols = -kvalue,names_to = "enzyme", values_to = "yield") %>% 
  separate(col = enzyme, into = c("param_type","enzyme"),sep = "_")

head(df_sens)




```

Plot data
```{r}
df_sens %>% 
  ggplot(aes(x=log10(kvalue),y=yield,color=param_type)) +
  geom_line() +
  facet_wrap(vars(enzyme)) +
  theme_bw() +
 # ylim(0,1) +
  xlab("k-value") +
  ylab("Molar yield (benzoate/PU)")

```

Plot km and kcat separately
```{r}
df_sens %>% 
  filter(param_type == "kcat") %>% 
  ggplot(aes(x=log10(kvalue),y=yield,color=param_type)) +
  geom_line(color = "#5A725A") +
  facet_wrap(vars(enzyme),scales = "free") +
  theme_classic() +
  ylim(0,1.5) +
  xlab("log10(k_value)") +
  ylab("Molar yield (benzoate/PU)") +
  ggtitle("k_cat values") +
  geom_vline(data = dummy2, aes(xintercept = Z), linetype = "dotted") 
 

  

 df_sens %>% 
  filter(param_type == "km") %>% 
  ggplot(aes(x=log10(kvalue),y=yield,color=param_type)) +
  geom_line(color = "#5A725A") +
  facet_wrap(vars(enzyme),scales = "free") +
  theme_classic() +
  ylim(0,1.5) +
  xlab("log10(k_value)") +
  ylab("Molar yield (benzoate/PU)") +
  ggtitle("k_m values") +
  geom_vline(data = dummy, aes(xintercept = Z), linetype="dotted") 
  
  


  
  


```

