---
title: "Kegg query"
output: html_notebook
---
 
Load libraries
```{r}
library(tidyverse)
library(KEGGREST)
select = dplyr::select
mutate = dplyr::mutate
rename = dplyr::rename
```

```{r}
modelEco <- read_excel("")

"/Desktop/iGEM/modelling/repository/iGEMChalmers2020/GEM/scrap/modelEco.xlsx"

```

 
List all KEGG ids
```{r}
kegg_ids = modelEco$`GENE ASSOCIATION`

kegg_ids = gsub(" .*","",kegg_ids)

kegg_ids = gsub("\\(","",kegg_ids)

kegg_ids = paste0("eco:",kegg_ids)


kegg_ids
```
 
dataframe to store results
```{r}
kegg_df = data.frame(gene_id = kegg_ids,
                     pathway_id = NA) %>% 
  mutate(gene_id = gsub("eco:NA",NA_character_,gene_id)) %>%
  mutate(gene_id = as.character(gene_id)) %>% 
  mutate(gene_id = gsub("eco:s0001",NA_character_,gene_id))
```
 
```{r}
module_id = NA
for (i in 2677:length(kegg_ids)) {
  #print(paste0("Gene ID: ",kegg_df$gene_id[i]))
  
  if (!is.na(kegg_df$gene_id[i])) {
    query <- keggGet(kegg_df$gene_id[i])
    module_id = query[[1]]$PATHWAY[[1]]
    
    if (!is.null(module_id)) {
      if (!is.na(module_id)) {
        kegg_df$pathway_id[i] = module_id
      }
    }
    module_id = NA
  }
}

head(kegg_df)

```

```{r}
kegg_df = kegg_df %>% 
  mutate(rxn_id = modelEco$ID)
```


```{r}
write_csv(kegg_df,na = "NA",path = "/Users/leti/Desktop/kegg_df.csv")
```




