---
title: "Visualize fluxes from random sampling"
author: "iGEM 2020"
output:
  html_document:
    df_print: kable
    toc: true
    toc_float: true
---
 
# Load libraries
```{r}
library(tidyverse)
library(cowplot)
library(ggpubr)
library(ggsci)
library(ggrepel)
library(ggExtra)
library(readxl)
library(ComplexHeatmap)
library(Rtsne)
select = dplyr::select
mutate = dplyr::mutate
```
 
```{r}
setwd("/Users/leti/Desktop/iGEM/modelling/repository/iGEMChalmers2020/GEM/")
```
 
# Load Data
Load pre-processed vcf data and metadata
```{r}
df_glu <- read_excel("/Users/leti/Desktop/iGEM/modelling/repository/iGEMChalmers2020/GEM/scrap/rxns_random_glu.xlsx")
df_pu <- read_excel("/Users/leti/Desktop/iGEM/modelling/repository/iGEMChalmers2020/GEM/scrap/rxns_random_pu.xlsx")
 
df_kegg = read_csv("/Users/leti/Desktop/iGEM/modelling/repository/iGEMChalmers2020/GEM/scrap/kegg_df.csv")
```
 
```{r}
df_full = 
  full_join(df_glu,df_pu,by = "rxns_names_fluxes")
head(df_full)
```
 
```{r}
df_long =
  df_full %>% 
  pivot_longer(cols = -rxns_names_fluxes,
               names_to = "solution",
               values_to = "flux") %>% 
  distinct()
```
 
 
```{r}
df_long %>% 
  filter(rxns_names_fluxes == "BIOMASS_Ec_iML1515_core_75p37M")
```
 
 
Get samples with non-zero biomass flux
```{r}
nonZero_samples = 
  df_long %>% 
  filter(rxns_names_fluxes == "BIOMASS_Ec_iML1515_core_75p37M") %>% 
  filter(flux > 0)
 
head(nonZero_samples)
```
Filter out all non zero samples
```{r}
df_long_nonzero = 
  nonZero_samples %>% 
  select(solution) %>% 
  left_join(df_long, by = c("solution" = "solution")) %>% 
  left_join(df_kegg, by = c("rxns_names_fluxes" = "rxn_id"))
```
 
Convert into wide format
```{r}
df_wide_nonzero =
  df_long_nonzero %>% 
  select(-c(gene_id,pathway_id)) %>% 
  pivot_wider(names_from = solution,
              values_from = flux) %>% 
  as.data.frame()
 
rownames(df_wide_nonzero) = df_wide_nonzero[,1]
df_wide_nonzero = df_wide_nonzero[,-1]
```
 
### Dimnesionality reduction
 
PCA
```{r}
pca1 = prcomp(t(df_wide_nonzero),center = TRUE)
 
plotData = pca1$x[,1:2]
plotData = cbind(solution = rownames(plotData),plotData)
rownames(plotData) = NULL
 
head(plotData)
 
sample_names = plotData[,1]
 
plotData %>% 
  as.tibble() %>% 
  mutate(condition = ifelse(grepl("Glu",solution),"Glucose","Polyurethane")) %>% 
  mutate(PC1 = as.double(PC1),
         PC2 = as.double(PC2)) %>% 
  ggplot(aes(x = PC1,y = PC2, color = condition, group = condition)) +
  geom_point()
```
 
tSNE
```{r}
tsne1 = Rtsne(t(df_wide_nonzero),
             dims = 2,
             perplexity = 20,
             theta = 0.5,
             check_duplicates = FALSE)
 
tsne1$Y
 
plotData =
  tsne1$Y %>% 
  as_tibble() %>% 
  mutate(solution = sample_names)
 
plotData = 
  plotData %>% 
  mutate(condition = ifelse(grepl("Glu",solution),"Glucose","Polyurethane")) %>% 
  mutate(V1 = as.double(V1),
         V2 = as.double(V2))
 
plotData %>% 
  ggplot(aes(x = V1,y = V2, color = condition, group = condition)) +
  geom_point() +
  xlab("tSNE 1") +
  ylab("tSNE 2") +
  theme_bw() +
  theme(legend.position = "bottom",
        aspect.ratio = 1,
        axis.text.x = element_blank(),
        axis.text.y = element_blank()) +
  scale_color_manual("Carbon source", values = c("darkorange1","deeppink4"))
```
 
Hierarchical clustering and heatmaps
```{r}
# Extract nonzero fluxes
nonZero_fluxes = 
  df_long_nonzero %>% 
  group_by(rxns_names_fluxes) %>% 
  summarize(zeroFlux = sum(flux) == 0) %>%
  ungroup() %>% 
  filter(zeroFlux == FALSE)
 
# Format for Heatmap
hm.data = df_long_nonzero %>% 
  right_join(nonZero_fluxes,by = "rxns_names_fluxes") %>% 
  select(rxns_names_fluxes,solution,flux) %>% 
  pivot_wider(names_from = solution,
              values_from = flux) %>% 
  arrange(rxns_names_fluxes) %>% 
  as.data.frame()
 
rownames(hm.data) = hm.data[,1]
hm.data = hm.data[,-1]
 
hm.data = as.matrix(hm.data)
 
# Get sample data for annotation
sample.cond = 
  plotData %>% 
  pull(condition)
 
pathway.annot = df_long_nonzero %>% 
  right_join(nonZero_fluxes,by = "rxns_names_fluxes") %>% 
  select(rxns_names_fluxes,pathway_id) %>%
  distinct() %>% 
  arrange(rxns_names_fluxes) %>% 
  pull(pathway_id)
 
# Create annotations for heatmap
ha.col = HeatmapAnnotation(Carbon_source = sample.cond,
                       col = list(Carbon_source = c(Glucose = "darkorange1", Polyurethane = "violetred")))
 
 
# Draw heatmap
hm = Heatmap(hm.data,
        name = "scaled-centered intesities",
        clustering_distance_rows = "euclidean", 
        clustering_distance_columns = "euclidean",
        show_column_names = FALSE,
        show_row_names = FALSE,
        top_annotation = ha.col,
        #left_annotation = ha.row,
        #col = col_fun,
        #column_dend_height = unit(25, "mm"),
        #row_dend_width = unit(25, "mm"),
        show_row_dend = TRUE,
        show_column_dend = TRUE)
 
hm
```
Wilcoxon tests
```{r, warning=F}
options(scipen = 1)
res_wilcox =
  df_long_nonzero %>%
  right_join(nonZero_fluxes, by = "rxns_names_fluxes") %>%
  mutate(condition = ifelse(grepl("Glu", solution), "Glucose", "Polyurethane")) %>%
  select(rxns_names_fluxes, flux, condition) %>%
  group_by(condition, rxns_names_fluxes) %>%
  summarise(flux = list(flux)) %>%
  pivot_wider(names_from = condition, values_from = flux) %>%
  group_by(rxns_names_fluxes) %>%
  mutate(
    p_value = wilcox.test(unlist(Glucose), unlist(Polyurethane))$p.value,
    fold_change = sign(median(unlist(Polyurethane), median(unlist(Glucose)))) * 
      abs(median(unlist(Polyurethane)) - median(unlist(Glucose)))
  ) %>%
  select(rxns_names_fluxes, p_value, fold_change) %>%
  mutate(FDR = p.adjust(p_value, method = "BH")) %>%
  filter(FDR < 0.05) %>%
  arrange(FDR)
```
 
Show wilcox test results
```{r}
df_long_nonzero %>% 
  right_join(nonZero_fluxes, by = "rxns_names_fluxes") %>%
  select(rxns_names_fluxes, pathway_id) %>% 
  inner_join(res_wilcox, by = "rxns_names_fluxes") %>% 
  distinct() %>% 
  arrange(FDR)
```
Filter out those with pathways
```{r}
df_long_nonzero %>% 
  right_join(nonZero_fluxes, by = "rxns_names_fluxes") %>%
  select(rxns_names_fluxes, pathway_id) %>% 
  inner_join(res_wilcox, by = "rxns_names_fluxes") %>% 
  distinct() %>%
  arrange(FDR) %>% 
  filter(!is.na(pathway_id))
```
 
```{r}
rxn_to_plot = "MALS"
 
df_long_nonzero %>%
  right_join(nonZero_fluxes, by = "rxns_names_fluxes") %>%
  mutate(condition = ifelse(grepl("Glu", solution), "Glucose", "Polyurethane")) %>%
  filter(rxns_names_fluxes == rxn_to_plot) %>% 
  ggplot(aes(x=condition,y=flux,color = condition, fill = condition)) +
  geom_jitter() +
  theme_ipsum_rc(axis = TRUE,
                 axis_title_face = "bold") +
  xlab("") +
  ylab("Flux (mmol/gDWh)") +
  theme(legend.position = "none") +
  scale_color_manual("Carbon source", values = c("darkorange1","deeppink4"))
```
 
```{r}
pathway_to_plot = "Pyruvate metabolism"
pathway_to_plot = "Glycolysis / Gluconeogenesis"
 
 
df_long_nonzero %>%
  right_join(nonZero_fluxes, by = "rxns_names_fluxes") %>%
  mutate(condition = ifelse(grepl("Glu", solution), "Glucose", "Polyurethane")) %>%
  filter(pathway_id == pathway_to_plot) %>% 
  ggplot(aes(x=condition,y=flux,color = condition, fill = condition)) +
  geom_jitter() +
  facet_wrap(~rxns_names_fluxes,
             scales = "free") +
  theme_ipsum_rc(axis = TRUE,
                 axis_title_face = "bold") +
  xlab("") +
  ylab("Flux (mmol/gDWh)") +
  theme(legend.position = "none") +
  scale_color_manual("Carbon source", values = c("darkorange1","deeppink4"))
```
```{r}
pathway_to_plot = "Porphyrin and chlorophyll metabolism"
 
df_long_nonzero %>%
  right_join(nonZero_fluxes, by = "rxns_names_fluxes") %>%
  mutate(condition = ifelse(grepl("Glu", solution), "Glucose", "Polyurethane")) %>%
  filter(pathway_id == pathway_to_plot) %>% 
  ggplot(aes(x=condition,y=flux,color = condition, fill = condition)) +
  geom_jitter() +
  facet_wrap(~rxns_names_fluxes,
             scales = "free") +
  theme_ipsum_rc(axis = TRUE,
                 axis_title_face = "bold") +
  xlab("") +
  ylab("Flux (mmol/gDWh)") +
  theme(legend.position = "none") +
  scale_color_manual("Carbon source", values = c("darkorange1","deeppink4"))
```
 
Plot heatmap of DE fluxes
```{r}
# Extract nonzero fluxes
nonZero_fluxes = 
  df_long_nonzero %>% 
  group_by(rxns_names_fluxes) %>% 
  summarize(zeroFlux = sum(flux) == 0) %>%
  ungroup() %>% 
  filter(zeroFlux == FALSE)
 
diffFluxes = 
  df_long_nonzero %>% 
  right_join(nonZero_fluxes, by = "rxns_names_fluxes") %>%
  select(rxns_names_fluxes, pathway_id) %>% 
  inner_join(res_wilcox, by = "rxns_names_fluxes") %>% 
  distinct() %>%
  arrange(FDR) %>%
  filter(FDR < 0.05)
 
# Format for Heatmap
hm.data = df_long_nonzero %>% 
  right_join(nonZero_fluxes,by = "rxns_names_fluxes") %>% 
  right_join(diffFluxes) %>% 
  select(rxns_names_fluxes,solution,flux) %>% 
  pivot_wider(names_from = solution,
              values_from = flux) %>% 
  arrange(rxns_names_fluxes) %>% 
  as.data.frame()
 
rownames(hm.data) = hm.data[,1]
hm.data = hm.data[,-1]
 
hm.data = as.matrix(hm.data)
 
# Get sample data for annotation
sample.cond = 
  plotData %>% 
  pull(condition)
 
pathway.annot = df_long_nonzero %>% 
  right_join(nonZero_fluxes,by = "rxns_names_fluxes") %>% 
  select(rxns_names_fluxes,pathway_id) %>%
  distinct() %>% 
  arrange(rxns_names_fluxes) %>% 
  pull(pathway_id)
 
# Create annotations for heatmap
ha.col = HeatmapAnnotation(Carbon_source = sample.cond,
                       col = list(Carbon_source = c(Glucose = "darkorange1", Polyurethane = "violetred")))
 
 
# Draw heatmap
hm = Heatmap(hm.data,
        name = "scaled-centered intesities",
        clustering_distance_rows = "euclidean", 
        clustering_distance_columns = "euclidean",
        show_column_names = FALSE,
        show_row_names = FALSE,
        top_annotation = ha.col,
        #left_annotation = ha.row,
        #col = col_fun,
        #column_dend_height = unit(25, "mm"),
        #row_dend_width = unit(25, "mm"),
        show_row_dend = TRUE,
        show_column_dend = TRUE)
 
hm
```
 
 
```{r}
df_long_nonzero %>% 
  right_join(nonZero_fluxes,by = "rxns_names_fluxes") %>% 
  mutate(condition = ifelse(grepl("Glu",solution),"Glucose","Polyurethane")) %>% 
  filter(rxns_names_fluxes == "ENO") %>% 
  group_by(condition) %>% 
  summarise(median(flux))
 
df_long_nonzero %>% 
  right_join(nonZero_fluxes,by = "rxns_names_fluxes") %>% 
  mutate(condition = ifelse(grepl("Glu",solution),"Glucose","Polyurethane")) %>% 
  filter(rxns_names_fluxes == "FESD1s") %>% 
  group_by(condition) %>% 
  summarise(median(flux))
```
 