---
title: "Creating meta3"
output: html_notebook
---



#Load library
```{r}

library(tidyverse)

```

#Data from study: Pinnell (3)
Loading file report tsv file
```{r}
file_report_3 <- read_delim("./3_pinell_filereport_read_run_PRJEB15404_tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(file_report_3)
```

Select only necessary columns from file report 
```{r}
file_report_3_select <- select(file_report_3, run_accession, sample_alias)
file_report_3_select
```
Change header name from run_accession to sample_id 
```{r}
colnames(file_report_3_select)[1] <- "sample_id"
colnames(file_report_3_select)[3] <- "sample_alias"
glimpse(file_report_3_select)
```
Adding "marine metagenome" as extra column 
```{r}
report3 <- add_column(file_report_3_select, "environment" = "marine metagenome", .after = "sample_id")
report3
```


Adding name of study as extra column [READY TO MERGE]
```{r}
meta3 <- add_column(report3, "study" = "L.J. Pinnell, J.W. Turner (2019)", .after = "sample_alias")
meta3
```
