---
title: "Creating a meta data file"
output: creating_meta_data
---

#Load library
```{r}

library(tidyverse)

```

#Data from study: Bryant (4)
Loading file report tsv file
```{r}
file_report_4 <- read_delim("./4_bryant_filereport_station_read_run_PRJNA318384_tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(file_report_4)
```

Loading table from article tsv file
```{r}
article_table_4 <- read_delim("./4_bryant_excel.tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(article_table_4)

```
Merge files by ID "Station"
```{r}
merged_tables_4 <- merge(file_report_4,article_table_4,by="Station")
merged_tables_4
```
```{r}
meta4 <- left_join(file_report_4, article_table_4, by = "Station",
copy=FALSE, suffix=c("file_report_4","article_table_4"))
```



#Data from study: Poretsky (5)
Loading file report tsv file
```{r}
file_report_5 <- read_delim("./5_poretsky_filereport_sample_read_run_PRJNA385831_tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(file_report_5)
```

Loading 3 tables from article tsv file 
```{r}
article_table_5_1 <- read_delim("./5_poretsky_excel1.tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(article_table_5_1)

article_table_5_2 <- read_delim("./5_poretsky_excel2.tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(article_table_5_2)

article_table_5_3 <- read_delim("./5_poretsky_excel3.tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(article_table_5_3)

```
Merge table 1 and 3 by ID "Sample"
```{r}
merged_tables_5 <- merge(article_table_5_1,article_table_5_3,by="Sample")
merged_tables_5
```



Merge table 3 with file report by ID "Sample"
```{r}
merged_tables_5_final <- merge(file_report_5,merged_tables_5,by="Sample")
merged_tables_5_final  #Does not show any rows when trying to merge
```

