---
title: "Creating meta1"
output: html_notebook
---

#Load library
```{r}

library(tidyverse)

```

#Data from study: Gupta (1)
Loading file report tsv file
```{r}
file_report_1 <- read_delim("./1_gupta_filereport_read_run_PRJNA388130_tsv.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
glimpse(file_report_1)
```

Select only necessary columns from file report 
```{r}
file_report_1_select <- select(file_report_1, run_accession, scientific_name, sample_alias)
file_report_1_select
```


Change header name from run_accession to sample_id 
```{r}
colnames(file_report_1_select)[2] <- "environment"
colnames(file_report_1_select)[1] <- "sample_id"
colnames(file_report_1_select)[3] <- "sample_alias"
glimpse(file_report_1_select)
```
Adding name of study as extra column [READY TO MERGE]
```{r}
meta1 <- add_column(file_report_1_select, "study" = "J. Gupta et al. (2017)", .after = "sample_alias")
meta1
```
Adding another id column eg. "s001_gup_mar" (number_study_environment)
```{r}

#add_column(meta1, "id" = as.character (1:2) , .after = "sample_id")

#meta1 <- cbind("id" = sprintf("%03d", 1:nrow(meta1)),meta1)


#meta1$id = paste0("s", meta1$id, "_gup", "_mar")
#meta1
```

