---
title: "Visualize fluxes from FBA"
author: "iGEM Chalmers 2020"
output:
  html_document:
    df_print: kable
    toc: true
    toc_float: true
---

# Load libraries
```{r}
library(tidyverse)
library(cowplot)
library(ggpubr)
library(ggplot2)
library(ggsci)
library(ggrepel)
library(ggExtra)
library(readxl)
library(ComplexHeatmap)
library(Rtsne)
library(RColorBrewer)
select = dplyr::select
mutate = dplyr::mutate
```

# Load Data
Load fba flux distribution data and metadata
```{r}
#normal media
df_glu <- read_excel("/Users/castilln/Desktop/igem/github/GEM/scripts/scrap/flux_distribution_fba_glu.xlsx")
df_pu <- read_excel("/Users/castilln/Desktop/igem/github/GEM/scripts/scrap/flux_distribution_fba_pu.xlsx")
df_pet <- read_excel("/Users/castilln/Desktop/igem/github/GEM/scripts/scrap/flux_distribution_fba_pet.xlsx")

#minimal media
df_glu_min <- read_excel("/Users/castilln/Desktop/igem/github/GEM/scripts/scrap/flux_distribution_fba_min_glu.xlsx")
df_pu_min <- read_excel("/Users/castilln/Desktop/igem/github/GEM/scripts/scrap/flux_distribution_fba_min_pu.xlsx")
df_pet_min <- read_excel("/Users/castilln/Desktop/igem/github/GEM/scripts/scrap/flux_distribution_fba_min_pet.xlsx")

#kegg query 
df_kegg = read_csv("/Users/castilln/Desktop/igem/github/GEM/Data/kegg_df.csv")
```
merge all distributions
```{r}
df_full = 
  full_join(df_glu, df_pu, by = "rxns_names")
df_full = full_join(df_full, df_pet, by ="rxns_names")

df_full %>% rename("Glucose" = fluxes_glu, "Polyurethane" = fluxes_pu, "PET" = fluxes_pet, "Rxns" = rxns_names) -> df_full

#minimal media
df_full_min = 
  full_join(df_glu_min, df_pu_min, by = "rxns_names")
df_full_min = full_join(df_full_min, df_pet_min, by ="rxns_names")

df_full_min %>% rename("Glucose minimal" = fluxes_min_glu, "Polyurethane minimal" = fluxes_min_pu, "PET minimal" = fluxes_min_pet, "Rxns" = rxns_names) -> df_full_min

```


Kruskal Wallis 
```{r}

df_full %>% pivot_longer(cols = c(Glucose, Polyurethane, PET), names_to = "C_source", values_to = "flux") -> kt_df

kruskal.test(flux ~ C_source , data = kt_df)

#for minimal media
df_full_min %>%  pivot_longer(cols = c(`Glucose minimal`, `Polyurethane minimal`, `PET minimal`), names_to = "C_source", values_to = "flux") -> kt_min_df

kruskal.test(flux ~ C_source, data = kt_min_df)

#significant differences between media? 
df_full %>% mutate(media = "standard") -> df_full
df_full_min %>% mutate(media = "minimal") -> df_full_min

#merge both df
df_full %>% pivot_longer(cols = c(Glucose, Polyurethane, PET), names_to = "C_source", values_to = "flux") -> kt_df
df_full_min %>%  pivot_longer(cols = c(`Glucose minimal`, `Polyurethane minimal`, `PET minimal`), names_to = "C_source", values_to = "flux") -> kt_min_df

df_media = rbind(kt_df, kt_min_df)

kruskal.test(flux ~ media, data = df_media)

```

#DE expression
FC & wilcox test
Consider flux as an absolute entity
```{r}
df_full %>% mutate(FC_pu = abs(Polyurethane) - abs(Glucose), FC_pet = abs(PET) - abs(Glucose)) -> df_fc #calculate FC

#wilcox test
options(scipen = 1)
df_fc %>% mutate(p_value_pu = wilcox.test(Glucose, Polyurethane)$p.value, p_value_pet = wilcox.test(Glucose, PET, paired = TRUE)$p.value, p_value_pu_pet = wilcox.test(Polyurethane, PET, paired = TRUE)$p.value) -> df_diff

df_diff %>% select(Rxns, FC_pu, p_value_pu) %>% arrange(FC_pu) -> df_pu #only FC and pvalue of PU vs glu
df_diff %>% select(Rxns, FC_pet, p_value_pet) %>% arrange(FC_pet) -> df_pet #only FC and pvalue of PET vs glu

#add pathways from kegg query
df_pu = df_pu %>% left_join(df_kegg, by = c("Rxns" = "rxn_id"))
df_pet = df_pet %>% left_join(df_kegg, by = c("Rxns" = "rxn_id"))

#minimal media
df_full_min %>% mutate(FC_pu = abs(`Polyurethane minimal`) - abs(`Glucose minimal`), FC_pet = abs(`PET minimal`) - abs(`Glucose minimal`)) -> df_min_fc 

options(scipen = 1)
df_min_fc %>% mutate(p_value_pu = wilcox.test(`Glucose minimal`, `Polyurethane minimal`, paired = TRUE)$p.value, p_value_pet = wilcox.test(`Glucose minimal`, `PET minimal`, paired = TRUE)$p.value, p_value_pu_pet = wilcox.test(`Polyurethane minimal`, `PET minimal`, paired = TRUE)$p.value) -> df_diff_min

df_diff_min %>% select(Rxns, FC_pu, p_value_pu) %>% arrange(FC_pu) -> df_pu_min
df_diff_min %>% select(Rxns, FC_pet, p_value_pet) %>% arrange(FC_pet) -> df_pet_min

df_pu_min = df_pu %>% left_join(df_kegg, by = c("Rxns" = "rxn_id"))
df_pet_min = df_pet %>% left_join(df_kegg, by = c("Rxns" = "rxn_id"))
```

#Wilcox test for different media
```{r}
df_full = df_full[-5] #remove media column
df_full_min = df_full_min[-5] #remove media column

df_full %>% left_join(df_full_min, by = "Rxns") -> df_full_both

#compare distributions in normal and minimal media (p-value)
options(scipen = 1)
df_full_both %>% mutate(p_value_glu = wilcox.test(Glucose, `Glucose minimal`, paired = TRUE)$p.value, p_value_pu = wilcox.test(Polyurethane, `Polyurethane minimal`, paired = TRUE)$p.value, p_value_pet = wilcox.test(PET, `PET minimal`, paired = TRUE)$p.value) -> df_full_both
```


### Calculate biochemical yield
```{r}
df_full %>%  filter(Rxns == "BIOMASS_Ec_iML1515_core_75p37M") %>% 
   pivot_longer(cols = c(Glucose, Polyurethane, PET)) -> biomass

df_full %>% filter(Rxns == "EX_glc__D_e") %>% select(Glucose) %>% pivot_longer(Glucose, values_to = "Consumption")  %>% right_join(biomass, by = "name") -> yield_glu

df_full %>% filter(Rxns == "EXC_BOTH_pu") %>% select(Polyurethane) %>% pivot_longer(Polyurethane, values_to = "Consumption")  %>% right_join(biomass, by = "name") -> yield_pu

df_full %>% filter(Rxns == "EXC_BOTH_pet") %>% select(PET) %>% pivot_longer(PET, values_to = "Consumption")  %>% right_join(biomass, by = "name") -> yield_pet

#for minimal media
df_full_min %>%  filter(Rxns == "BIOMASS_Ec_iML1515_core_75p37M") %>% 
   pivot_longer(cols = c(`Glucose minimal`, `Polyurethane minimal`, `PET minimal`)) -> biomass_min

df_full_min %>% filter(Rxns == "EX_glc__D_e") %>% select(`Glucose minimal`) %>% pivot_longer(`Glucose minimal`, values_to = "Consumption")  %>% right_join(biomass_min, by = "name") -> yield_glu_min

df_full_min %>% filter(Rxns == "EXC_BOTH_pu") %>% select(`Polyurethane minimal`) %>% pivot_longer(`Polyurethane minimal`, values_to = "Consumption")  %>% right_join(biomass_min, by = "name") -> yield_pu_min

df_full_min %>% filter(Rxns == "EXC_BOTH_pet") %>% select(`PET minimal`) %>% pivot_longer(`PET minimal`, values_to = "Consumption")  %>% right_join(biomass_min, by = "name") -> yield_pet_min


##yield
yield_glu = yield_glu %>% filter(name == "Glucose") %>% mutate(yield = value / (abs(Consumption)*0.18016))
yield_pu = yield_pu %>% filter(name == "Polyurethane") %>% mutate(yield = value / (abs(Consumption)*0.31232))
yield_pet = yield_pet %>% filter(name == "PET") %>% mutate(yield = value / (abs(Consumption)*0.1922))


##Yield for minimal media
yield_glu_min = yield_glu_min %>% filter(name == "Glucose minimal") %>% mutate(yield = value / abs(Consumption))
yield_pu_min = yield_pu_min %>% filter(name == "Polyurethane minimal") %>% mutate(yield = value / abs(Consumption))
yield_pet_min = yield_pet_min %>% filter(name == "PET minimal") %>% mutate(yield = value / abs(Consumption))


total_yield = rbind(yield_glu, yield_glu_min, yield_pu,yield_pu_min, yield_pet, yield_pet_min) %>% 
  rename("Condition" = name) 


view(total_yield)
```
set palette
```{r}
brewer.pal(n = 8, name = "Dark2")
palette(brewer.pal(n = 8, name = "Dark2")) #load palette
```


Plot yield
```{r, fig.width=10,fig.height=8}
options(digits = 2) 
ggsci::pal_lancet(palette = c("lanonc"), alpha = 1)
ggplot(total_yield, aes(x = Condition, y = yield, label=sprintf("%0.2f", round(yield, digits = 4)))) +
  geom_col(fill = "#5A725A") + 
  geom_text(position = position_dodge(0.5), hjust = -0.08, size = 3.7) +
  theme_bw() + 
  ggtitle("Theoretical yields on different C sources and media") +
  #scale_fill_manual(values = c("#669933", "#66CC99", "#66CC99", "#66CC99","#66CC99","#66CC99")) +
  theme(legend.position = "none",
        aspect.ratio = 1,
        plot.title = element_text(face = "bold"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  ylab("Yield (gDW/g of C)") +
  xlab("Carbon source") +
  coord_flip() -> fba_yield

    ggsave("fba_yield.png", device = "png", width = 25, height = 15, units = "cm", dpi = "retina")

```

